### ISSUE TITLE
ControllerAction for AppClientDisplayAdapter throws exception.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#10]
Build info:

appgen": "@encapsule/holistic v0.0.46 crossroads 8Ei6heL7RE66YL0q5jkslw 450d4fe4c7db0085ce31b323b0d4eb70fff1eac6 2020-09-26T22:55:07.000Z",

The controller action: 

https://github.com/Encapsule/holistic/blob/v0.0.46-crossroads/PACKAGES/holistic-app-client-cm/AppClientDisplayAdapter/ControllerAction-react-render-client-view.js#L58

Throws and exception " ... holarchy is undefined" from line 58 shown above.

**Comment by ChrisRus** [comment]
Relates to current work to update @encapsule/holistic-app-client-cm AppClientDisplayAdaptor CellModel.

**Comment by phil-kahrl** [comment]
Fixed with the new Display Adapter in the alexandrite branch.
