### ISSUE TITLE
AppClientDisplayAdapter - Incorrect transition operator signature in apm.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#11]
Build info:

appgen": "@encapsule/holistic v0.0.46 crossroads 8Ei6heL7RE66YL0q5jkslw 450d4fe4c7db0085ce31b323b0d4eb70fff1eac6 2020-09-26T22:55:07.000Z",

Exception is being thrown on evaluation of transition operator in the apm declaration:

https://github.com/Encapsule/holistic/blob/v0.0.46-crossroads/PACKAGES/holistic-app-client-cm/AppClientDisplayAdapter/AbstractProcessModel-app-client-display-adapter.js#L297

The signature at the above line should be "cell" instead of "opmi"

**Comment by ChrisRus** [comment]
Relates to ongoing work on @encapsule/holistic-app-client-cm RTL AppClientDisplayAdaptor.

**Comment by phil-kahrl** [comment]
Fixed with the new Display Adapter in the alexandrite branch.
