### ISSUE TITLE
cellProcessQuery does not find singleton instance unless "singleton" is explicitly passed.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#13]
Build info:

"appgen": "@encapsule/holistic v0.0.46 crossroads KdclOLg3SyqYSF6u2YUbDg 8e52b7dc753f874256a631b2244721553e41a5dd 2020-09-29T18:58:04.000Z",

When starting a cell process using:

`
                     holarchy: {
                        CellProcessor: {
                            process: {
                                create: {
                                    apmID: "12345 ..."
                                }
                            }
                        }
                    }
`

A "cellProcessUniqueName" is not required, the name is defaulted to "singleton" by the cpm.

When I go to query for the same process, I have to pass in "singleton" for "cellProcesssUniqueName" or the query will not find the process.  In other words:

`            holarchy: {
                    CellProcessor: {
                        process: {
                            query: {
                                queryCellProcess: {
                                    cellProcessNamespace: {
                                        apmID,
                                        //TODO this shouldn't be required after upgrading to the latest version of holistic.
                                        cellProcessUniqueName: "singleton"
                                    }
                                }
                            }
                        }
                    }
                }
`

Works whereas:

`                holarchy: {
                    CellProcessor: {
                        process: {
                            query: {
                                queryCellProcess: {
                                    cellProcessNamespace: {
                                        apmID,
                                    }
                                }
                            }
                        }
                    }
                }
`

does not.

If I am not required to pass in a unique name to create the process, I should not be required to pass in the uniqueName to query it.  Getting the query to work requires me to know the default name that is being used by the CPM.

**Comment by ChrisRus** [comment]
Updated cellProcessNamespace.cellProcessUniqueName spec to default to "singleton". I had missed this case (now consistent w/process create and delete)
