### ISSUE TITLE
CellProcess Proxy Connect throws exception if appdsl apm is missing.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#14]
Build info:

"appgen": "@encapsule/holistic v0.0.46 crossroads KdclOLg3SyqYSF6u2YUbDg 8e52b7dc753f874256a631b2244721553e41a5dd 2020-09-29T18:58:04.000Z",

When using cell process process connect: e.g.

`holarchy: {
       CellProcessProxy: {
                 connect: {
                                proxyPath: "#.something"
                                     localCellProcess: {
                                              apmID: "foobar",
                                     }
                            }
                     }
       }`

If the namespace defined by "proxyPath" does not have "____appdsl: apm: " ....", an error should be returned.

However instead of an error being returned and uncaught exception is thrown: "Handled exception during controller action dispatch: Cannot read property 'apm' of undefined"

The root cause of the exception is here:  

https://github.com/Encapsule/holistic/blob/v0.0.46-crossroads/PACKAGES/holarchy/lib/intrinsics/CellProcessProxy/lib/cpp-get-status-filter.js#L82

Because in the expression the second condition throws and error because `proxyMemorySpec.____appdsl` will be undefined.

**Comment by ChrisRus** [comment]
Changed the && to ||. Try again in next test release please.
