### ISSUE TITLE
ocd writeNamespace filter throw on attempt to write to an empty map entry

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#15]
Build info:

appgen": "@encapsule/holistic v0.0.46 crossroads KdclOLg3SyqYSF6u2YUbDg 8e52b7dc753f874256a631b2244721553e41a5dd 2020-09-29T18:58:04.000Z",

If in an ocd namespace you have a map declared:

`myMap: {
    ____types: "jsObject",
    ____asMap: true,
   ____defaultValue: {}
  key: {____accept: "jsObject"}
}`

If you attempt to write to a key in the map that doesn't exist such as:
( "key1" is not in the map)

`ocd.writeNamespace("~...myMap.key1", {foo: "bar"})`

Then the writeNamespace filter will throw an exception instead of returning an error as it should.

**Comment by ChrisRus** [comment]
If you can repro, please include the exception and stack trace.

**Comment by phil-kahrl** [comment]
Sample exception below from trying to write to non-existent key "notakey" in a map in OCD.

ReferenceError: notakey is not defined
    at Object.bodyFunction (ControllerAction-initialize-table.js:159)
    at t.value (arc_core_lib.js:1)
    at Object.bodyFunction (opc-method-act-filter.js:137)
    at t.value (arc_core_lib.js:1)
    at ObservableProcessController.act (ObservableProcessController.js:202)
    at Table.componentDidMount (Table.jsx:100)
    at commitLifeCycles (react-dom.development.js:22101)
    at commitLayoutEffects (react-dom.development.js:25344)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)

**Comment by ChrisRus** [comment]
I added a test harness of OCD and wrote a unit test to check this specific case (note that OCD has barely changed since 2018).

In the next test release to vp5 checkout platform test vector "in2UzfF3QiG3_NJHRPEhag"

Does you usable differ from this test case?
Have you stepped into the method to figure out why it's failing?

**Comment by phil-kahrl** [comment]
On closer examination, there is no exception being thrown in ocdi.writeNamespace, the exception was being thrown in the bodyFunction of the controller action due to an undefined variable inside a template expression.

**Comment by phil-kahrl** [comment]
I do remember seeing an exception inside the writeNamespace function at some point, but I am not currently able to reproduce, so this issue can remain closed unless the same circumstance is encountered again.
