### ISSUE TITLE
ocd readNamespace filter throw exception when trying to read non-existent namespace.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#18]
Build info:

"appgen": "@encapsule/holistic v0.0.46 crossroads t10PUwZHS3e8dhu3oBpMRA 10e623d9d2dbfb86af25bf3795dc8ec73e9af666 2020-10-08T18:50:20.000Z",

The issue can be seen in the branch below, where the test vector was added and test output is from the "testPlatform" target.

https://github.com/Viewpath/viewpath5/compare/platform/crossroads/head...readnamespace-bug?expand=1

**Comment by ChrisRus** [comment]
Fixed in v0.0.47-alexandrite
