### ISSUE TITLE
Include client.js from appGen script when creating a new derived repo.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#5]
Build info:

"appgen": "@encapsule/holistic v0.0.46 crossroads CfA9bf7rR6WKBhqnhjgKWw 99ccf316fd664cd9fd66c9c624a3524ae95158cd 2020-09-23T21:44:33.000Z",

To reproduce:

1.  Create a new git repo by running `yarn init` and `git init`.
2.  Run holistic appgen with `appRepoDir` set to the new local repo directory,
3.  Add and commit all files in the derived repo.
4.  Run `yarn build` on the derived repo.

The following error will result:

`ERROR in Entry module not found: Error: Can't resolve '/Users/viewpathuser/workspace2/holistic-bugs/BUILD/transpile-phase1/CLIENT/client.js' in '/Users/viewpathuser/workspace2/holistic-bugs'
resolve '/Users/viewpathuser/workspace2/holistic-bugs/BUILD/transpile-phase1/CLIENT/client.js' in '/Users/viewpathuser/workspace2/holistic-bugs'`

An empty or skeleton "client.js" should be included from appgen so that the derived repo will build initially.

**Comment by ChrisRus** [comment]
The intent (long-term) is to write SOURCES/SERVER/server.js and SOURCES/CLIENT/client.js with boilerplate files that initialize respective CellProcessor instances, and boot the app server and client kernel processes respectively. This will get you a running baseline application that you can extend by adding custom CellModel.

But for now, just `touch client.js` ;-)
