### ISSUE TITLE
cpm process query throws exception instead of returning error.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#6]
Build:

"appgen": "@encapsule/holistic v0.0.46 crossroads CfA9bf7rR6WKBhqnhjgKWw 99ccf316fd664cd9fd66c9c624a3524ae95158cd 2020-09-23T21:44:33.000Z",

An exception is thrown when using the cpm query controller action:

https://github.com/Encapsule/holistic/blob/v0.0.46-crossroads/PACKAGES/holarchy/lib/intrinsics/CellProcessManager/ControllerAction-cpm-process-query.js

If the query is unable to find the requested process, instead of returning an error an unhandled exception is encountered:

"ERROR in 4 ms: Handled exception during controller action dispatch: repsonse is not defined" 

which is originating from here: https://github.com/Encapsule/holistic/blob/v0.0.46-crossroads/PACKAGES/holarchy/lib/intrinsics/CellProcessManager/lib/cpm-get-cell-process-descriptor.js#L64

**Comment by ChrisRus** [comment]
I found several instances of the repsonse vs response typo and fixed them in next test release.
