### ISSUE TITLE
ComponentRouter  React Component should not require context theme specific to ComponentRouter.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#7]
Build:

 "appgen": "@encapsule/holistic v0.0.46 crossroads CfA9bf7rR6WKBhqnhjgKWw 99ccf316fd664cd9fd66c9c624a3524ae95158cd 2020-09-23T21:44:33.000Z",

ComponentRouter:

https://github.com/Encapsule/holistic/blob/v0.0.46-crossroads/PACKAGES/d2r2/lib/ComponentRouter.jsx#L168

Currently requires specific themes e.g. `metadata.site.theme.ComponentRouterError...` to be present in the render context to correctly render if an error occurs such as not finding a registered r2d2 component for the render message.  In the absence of the correct theme in the render context, the ComponentRouter React component throws and renders nothing.

It is not reasonable for consumers of ComponentRouter to be aware and provide themes specific to ComponentRouter in the renderContext in order for it to properly handle errors.

**Comment by ChrisRus** [comment]
I am aware of a lot of very old cruft that remains in the Node.js-based @encapsule/holism integration filter definitions that must get unsnarled and exorcised from the codebase. This stacks up behind @encapsule/holarchy cell composition patterns, rework of @encapsule/holistic-app-client-cm AppClientKernel and its owned processes (DOMLocationProcessor, AppClientDisplayAdaptor...)

We have discussed in small detail the issue of styles. I will need to look at this subproblem again specifically once we have AppClientDisplayAdaptor ---> monitors for change ---> AppClientDisplayDriver
                                         <--- reads the new d2r2 value <---
pattern squared off. Then it becomes an issue to decide how all the React components mounted in the VDOM will be styled consistently and dynamically. And, ultimately this becomes a concern of what we're calling a View cell process.

... where a View cell process is a specific type of cell process that among other things may be registered as an AppClientDisplayDriver w/AppClientDisplayAdapter

**Comment by phil-kahrl** [comment]
The same issue applies for d2r2 components under @encapsule/d2r2 components.  In particular "HolisticPageView.jsx" requires 

        HolisticPageView: {
            container: {}
        }

**Comment by phil-kahrl** [comment]
Closing this issue since the theme settings have been removed from the ComponentRouter implementation in alexandrite build and "HolisticPageView.jsx" there may be some theme references in other d2r2 components but those can be addresses separately if they become an issue.
