### ISSUE TITLE
AppClientDisplayAdapter failing to initialize with TransitionOperator returning error.

### ISSUE THREAD

**Issue by phil-kahrl** [Encapsule/holistic#8]
Build info:

"appgen": "@encapsule/holistic v0.0.46 crossroads 8Ei6heL7RE66YL0q5jkslw 450d4fe4c7db0085ce31b323b0d4eb70fff1eac6 2020-09-26T22:55:07.000Z",

OPC::evaluate <gRyJ...> [2:1] TransitionOperator request was successfully parsed and routed to plug-in filter delegate [9tNY7o5GTUGH_xda2GhP-w::Cell Process In Step Operator]. But, the plug-in rejected the request with error: Filter [9tNY7o5GTUGH_xda2GhP-w::Cell Process In Step Operator] failed while performing main operation. Filter [RNUkdw8VT8WLz5H_i-SwYg::Data Path Resolve Filter] failed while performing main operation. Invalid dataPath '#.//.//.//.//' references namespace at or above the anonymous '~' namespace.

Offending code:

https://github.com/Encapsule/holistic/blob/v0.0.46-crossroads/PACKAGES/holistic-app-client-cm/AppClientDisplayAdapter/AbstractProcessModel-app-client-display-adapter.js#L96

**Comment by ChrisRus** [comment]
So, noted. All issues related to @encapsule/holistic-app-client-cm AppClientDisplayAdapter CellModel are in flux currently the the entire Holistic App Client Kernel (of which AppClientDisplayAdapter is one of several of the kernel's owned worker cell processes) are being reworked per latest @encapsule/holarchy cell composition patterns. We should have this resolved fairly shortly.

**Comment by phil-kahrl** [comment]
Fixed with the new Display Adapter in the alexandrite branch.
